# Use the official Python image as base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install required Python packages
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8000 to allow communication to/from the Flask app
EXPOSE 8000


# Command to run the Flask application
CMD ["python", "app.py"]
