apiVersion: v1
kind: Service
metadata:
  name: business-api
spec:
  type: NodePort
  selector:
    app: business-api
  ports:
    - port: 5000
      nodePort: 30500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-api
  template:
    metadata:
      labels:
        app: business-api
    spec:
      containers:
        - name: business-api
          image: mariamhsein/manufacturing_ai:businesses
          
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DEFECT_DETECTION_URL
              value: "http://defect-api:5001/detect_defects"
            - name: PREDICT_FAILURE_URL
              value: "http://failure-api:5002/predict_failure"

---
apiVersion: v1
kind: Service
metadata:
  name: defect-api
spec:
  type: NodePort
  selector:
    app: defect-api
  ports:
    - port: 5001
      nodePort: 30501
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: defect-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: defect-api
  template:
    metadata:
      labels:
        app: defect-api
    spec:
      containers:
        - name: defect-api
          image: mariamhsein/manufacturing_ai:detection
          stdin: true
          tty: true
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
---
---
apiVersion: v1
kind: Service
metadata:
  name: failure-api
spec:
  type: NodePort
  selector:
    app: failure-api
  ports:
    - port: 5002
      nodePort: 30502
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failure-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failure-api
  template:
    metadata:
      labels:
        app: failure-api
    spec:
      containers:
        - name: failure-api
          image: mariamhsein/manufacturing_ai:prediciton_failure
          stdin: true
          tty: true
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
---